from __future__ import annotations

from datetime import datetime, timezone
from typing import TYPE_CHECKING, Optional
import uuid

from sqlmodel import Field, Relationship, SQLModel
from sqlalchemy.orm import Mapped
from passlib.context import CryptContext

if TYPE_CHECKING:
    from backend.app.db.models.task import Task

# Password hashing context
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")


def generate_uuid() -> str:
    return str(uuid.uuid4())


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


class UserBase(SQLModel):
    email: str = Field(unique=True, index=True, nullable=False, max_length=255)
    name: Optional[str] = Field(default=None, max_length=255)


class User(UserBase, table=True):
    __tablename__ = "users"

    id: str = Field(default_factory=generate_uuid, primary_key=True, nullable=False)  # Using string ID from JWT - will be generated by DB

    # Add password field
    hashed_password: str = Field(nullable=False, max_length=255)

    # Relationship to tasks - temporarily commented out to resolve initialization error
    # tasks: Mapped[list['Task']] = Relationship(sa_relationship_kwargs={"lazy": "select"})

    created_at: datetime = Field(default_factory=utc_now, nullable=False)
    updated_at: datetime = Field(default_factory=utc_now, nullable=False)

    def verify_password(self, plain_password: str) -> bool:
        """Verify a plain password against the hashed password."""
        return pwd_context.verify(plain_password, self.hashed_password)

    @classmethod
    def hash_password(cls, password: str) -> str:
        """Hash a plain password."""
        return pwd_context.hash(password)